version: "3"
services:
  rucioclient:
    platform: linux/x86_64
    #image: docker.io/rucio/rucio-dev:latest-alma9
    image: docker.io/rucio/rucio-dev:release-33.5.0
    entrypoint: ["/rucio_source/etc/docker/dev/rucio_entrypoint.sh"]
    command: ["sleep", "infinity"]
    profiles:
      - client
    volumes:
      - ../../certs/rucio_ca.pem:/etc/grid-security/certificates/5fca1cb1.0:z
      - ../../certs/hostcert_rucio.pem:/etc/grid-security/hostcert.pem:z
      - ../../certs/hostcert_rucio.key.pem:/etc/grid-security/hostkey.pem:z
      - ../../certs/rucio_ca.pem:/opt/rucio/etc/rucio_ca.pem:z
      - ../../certs/ruciouser.pem:/opt/rucio/etc/usercert.pem:z
      - ../../certs/ruciouser.key.pem:/opt/rucio/etc/userkey.pem:z
      - ../../certs/ruciouser.certkey.pem:/opt/rucio/etc/usercertkey.pem:z
      - ../../certs/ssh/ruciouser_sshkey.pub:/root/.ssh/ruciouser_sshkey.pub:z
      - ../../certs/ssh/ruciouser_sshkey:/root/.ssh/ruciouser_sshkey:z
      - ../../../tools:/opt/rucio/tools:Z
      - ../../../bin:/opt/rucio/bin:Z
      - ../../../lib:/opt/rucio/lib:Z
      - ../../../tests:/opt/rucio/tests:Z
      - ../../../:/rucio_source:ro
      #- ../../../../modfiles/httpd.conf:/etc/httpd/conf/httpd.conf:z
      - ../../../../ctrl_rucio_ingest/etc/rucio.cfg:/opt/rucio/etc/rucio.cfg:z
      - ../../../../ctrl_rucio_ingest/lib/rucio/common/schema/lsst.py:/opt/rucio/lib/rucio/common/schema/lsst.py:z
      - ../../../../ctrl_rucio_ingest/lib/rucio/common/constants.py:/opt/rucio/lib/rucio/common/constants.py:z
      - ../../../../ctrl_rucio_ingest/lib/rucio/rse/protocols/protocol.py:/opt/rucio/lib/rucio/rse/protocols/protocol.py:z
      - ../../../../test_data:/opt/rucio/test_data
      - ../../../../disks:/rucio/disks
    environment:
      - RUCIO_SOURCE_DIR=/rucio_source
      - X509_USER_CERT=/opt/rucio/etc/usercert.pem
      - X509_USER_KEY=/opt/rucio/etc/userkey.pem
      - RDBMS
  rucio:
    #image: docker.io/rucio/rucio-dev:latest-alma9
    platform: linux/x86_64
    image: docker.io/rucio/rucio-dev:release-33.5.0
    # entrypoint: ["/rucio_source/etc/docker/dev/rucio_entrypoint.sh"]
    command: ["httpd","-D","FOREGROUND"]
    volumes:
      - ../../certs/rucio_ca.pem:/etc/grid-security/certificates/5fca1cb1.0:z
      - ../../certs/hostcert_rucio.pem:/etc/grid-security/hostcert.pem:z
      - ../../certs/hostcert_rucio.key.pem:/etc/grid-security/hostkey.pem:z
      - ../../certs/rucio_ca.pem:/opt/rucio/etc/rucio_ca.pem:z
      - ../../certs/ruciouser.pem:/opt/rucio/etc/usercert.pem:z
      - ../../certs/ruciouser.key.pem:/opt/rucio/etc/userkey.pem:z
      - ../../certs/ruciouser.certkey.pem:/opt/rucio/etc/usercertkey.pem:z
      - ../../certs/ssh/ruciouser_sshkey.pub:/root/.ssh/ruciouser_sshkey.pub:z
      - ../../certs/ssh/ruciouser_sshkey:/root/.ssh/ruciouser_sshkey:z
      - ../../../tools:/opt/rucio/tools:Z
      - ../../../bin:/opt/rucio/bin:Z
      - ../../../lib:/opt/rucio/lib:Z
      - ../../../tests:/opt/rucio/tests:Z
      - ../../../:/rucio_source:ro
      #- ../../../../modfiles/httpd.conf:/etc/httpd/conf/httpd.conf:z
      - ../../../../ctrl_rucio_ingest/etc/rucio.cfg:/opt/rucio/etc/rucio.cfg:z
      - ../../../../ctrl_rucio_ingest/lib/rucio/common/schema/lsst.py:/opt/rucio/lib/rucio/common/schema/lsst.py:z
      - ../../../../ctrl_rucio_ingest/lib/rucio/common/constants.py:/opt/rucio/lib/rucio/common/constants.py:z
      - ../../../../ctrl_rucio_ingest/lib/rucio/rse/protocols/protocol.py:/opt/rucio/lib/rucio/rse/protocols/protocol.py:z
      - ../../../../test_data:/opt/rucio/test_data
      - ../../../../disks:/rucio/disks
    environment:
      - PYTHONPATH=${PYTHONPATH}:/opt/permissions/rubin
      - RUCIO_SOURCE_DIR=/rucio_source
      - X509_USER_CERT=/opt/rucio/etc/usercert.pem
      - X509_USER_KEY=/opt/rucio/etc/userkey.pem
      - RDBMS
  ruciodb:
    platform: linux/x86_64
    image: docker.io/postgres:14
    environment:
      - POSTGRES_USER=rucio
      - POSTGRES_DB=rucio
      - POSTGRES_PASSWORD=secret
    command: ["-c", "fsync=off","-c", "synchronous_commit=off","-c", "full_page_writes=off"]
  graphite:
    image: docker.io/graphiteapp/graphite-statsd
  influxdb:
    platform: linux/x86_64
    image: docker.io/influxdb:latest
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=myusername
      - DOCKER_INFLUXDB_INIT_PASSWORD=passwordpasswordpassword
      - DOCKER_INFLUXDB_INIT_ORG=rucio
      - DOCKER_INFLUXDB_INIT_BUCKET=rucio
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
  elasticsearch:
    image: docker.io/elasticsearch:7.4.0
    environment:
      - discovery.type=single-node
  activemq:
    image: docker.io/webcenter/activemq:latest
    environment:
      - ACTIVEMQ_CONFIG_NAME=activemq
      - ACTIVEMQ_CONFIG_DEFAULTACCOUNT=false
      - ACTIVEMQ_USERS_fts=supersecret
      - ACTIVEMQ_GROUPS_writes=fts
      - ACTIVEMQ_USERS_receiver=supersecret
      - ACTIVEMQ_GROUPS_reads=receiver
      - ACTIVEMQ_CONFIG_SCHEDULERENABLED=true
      - ACTIVEMQ_USERS_hermes=supersecret
      - ACTIVEMQ_CONFIG_QUEUES_events=/queue/events'
  postgres14:
    image: docker.io/postgres:14
    profiles:
      - postgres14
    environment:
      - POSTGRES_USER=rucio
      - POSTGRES_DB=rucio
      - POSTGRES_PASSWORD=rucio
    command: ["-c", "fsync=off","-c", "synchronous_commit=off","-c", "full_page_writes=off"]
  mysql8:
    image: docker.io/mysql:8
    profiles:
      - mysql8
    environment:
      - MYSQL_USER=rucio
      - MYSQL_PASSWORD=rucio
      - MYSQL_ROOT_PASSWORD=rucio
      - MYSQL_DATABASE=rucio
      - MYSQL_TCP_PORT=3308
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--character-set-server=latin1"
  oracle:
    image: docker.io/gvenzl/oracle-xe:18.4.0
    profiles:
      - oracle
    environment:
      - ORACLE_PASSWORD=rucio
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
      - processes=1000
      - sessions=1105
      - transactions=1215
    volumes:
      - ./oracle_setup.sh:/container-entrypoint-initdb.d/oracle_setup.sh:Z
  fts:
    #image: docker.io/rucio/fts
    platform: linux/x86_64
    image: docker.io/rucio/fts:33.5.0
    profiles:
      - storage
    volumes:
      - ../../certs/rucio_ca.pem:/etc/grid-security/certificates/5fca1cb1.0:z
      - ../../certs/hostcert_fts.pem:/etc/grid-security/hostcert.pem:Z
      - ../../certs/hostcert_fts.key.pem:/etc/grid-security/hostkey.pem:Z
    ulimits:
      nofile:
        soft: 10240
        hard: 10240
  ftsdb:
    platform: linux/x86_64
    image: docker.io/mysql:8
    profiles:
      - storage
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_USER=fts
      - MYSQL_PASSWORD=fts
      - MYSQL_ROOT_PASSWORD=fts
      - MYSQL_DATABASE=fts
  xrd1:
    #image: docker.io/rucio/xrootd
    platform: linux/x86_64
    image: docker.io/rucio/xrootd:33.5.0
    profiles:
      - storage
    environment:
      - XRDPORT=1094
    volumes:
      - ../../certs/rucio_ca.pem:/etc/grid-security/certificates/5fca1cb1.0:z
      - ../../certs/hostcert_xrd1.pem:/tmp/xrdcert.pem:Z
      - ../../certs/hostcert_xrd1.key.pem:/tmp/xrdkey.pem:Z
      - ../../../../disks/xrd1/rucio:/rucio
    ulimits:
      nofile:
        soft: 10240
        hard: 10240
  xrd2:
    #image: docker.io/rucio/xrootd
    platform: linux/x86_64
    image: docker.io/rucio/xrootd:33.5.0
    profiles:
      - storage
    environment:
      - XRDPORT=1095
    volumes:
      - ../../certs/rucio_ca.pem:/etc/grid-security/certificates/5fca1cb1.0:z
      - ../../certs/hostcert_xrd2.pem:/tmp/xrdcert.pem:Z
      - ../../certs/hostcert_xrd2.key.pem:/tmp/xrdkey.pem:Z
      - ../../../../disks/xrd2/rucio:/rucio
    ulimits:
      nofile:
        soft: 10240
        hard: 10240
  xrd3:
    #image: docker.io/rucio/xrootd
    platform: linux/x86_64
    image: docker.io/rucio/xrootd:33.5.0
    profiles:
      - storage
    environment:
      - XRDPORT=1096
    volumes:
      - ../../certs/rucio_ca.pem:/etc/grid-security/certificates/5fca1cb1.0:z
      - ../../certs/hostcert_xrd3.pem:/tmp/xrdcert.pem:Z
      - ../../certs/hostcert_xrd3.key.pem:/tmp/xrdkey.pem:Z
      - ../../../../disks/xrd3/rucio:/rucio
    ulimits:
      nofile:
        soft: 10240
        hard: 10240
  xrd4:
    #image: docker.io/rucio/xrootd
    platform: linux/x86_64
    image: docker.io/rucio/xrootd:33.5.0
    profiles:
      - storage
    environment:
      - XRDPORT=1097
    volumes:
      - ../../certs/rucio_ca.pem:/etc/grid-security/certificates/5fca1cb1.0:z
      - ../../certs/hostcert_xrd4.pem:/tmp/xrdcert.pem:Z
      - ../../certs/hostcert_xrd4.key.pem:/tmp/xrdkey.pem:Z
      - ../../../../disks/xrd4/rucio:/rucio
    ulimits:
      nofile:
        soft: 10240
        hard: 10240
  minio:
    image: docker.io/minio/minio
    profiles:
      - storage
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - ../../certs/hostcert_minio.pem:/root/.minio/certs/public.crt:Z
      - ../../certs/hostcert_minio.key.pem:/root/.minio/certs/private.key:Z
    command: ["server", "/data"]
  ssh1:
    image: docker.io/rucio/ssh
    profiles:
      - storage
    volumes:
      - ../../certs/ssh/ruciouser_sshkey.pub:/tmp/sshkey.pub:Z
  mongo:
    image: docker.io/mongo:5.0
    profiles:
      - externalmetadata
  postgres:
    image: docker.io/postgres:14
    profiles:
      - externalmetadata
    environment:
      - POSTGRES_USER=rucio
      - POSTGRES_DB=metadata
      - POSTGRES_PASSWORD=secret
    command: ["-p", "5433"]
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.3.2
    profiles:
      - monitoring
    command: bash -c "logstash-plugin install logstash-input-stomp ; /usr/local/bin/docker-entrypoint"
    volumes:
      - ./pipeline.conf:/usr/share/logstash/pipeline/pipeline.conf:Z
  kibana:
    image: docker.io/kibana:7.4.0
    profiles:
      - monitoring
  grafana:
    image: docker.io/grafana/grafana:latest
    profiles:
      - monitoring
  db-iam:
    image: mariadb:10.11
    profiles:
      - iam
    environment:
      - TZ=Europe/Paris
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_USER=iam
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=iam_db
  nginx-iam:
    image: nginx
    profiles:
      - iam
    dns_search: cern.ch
    environment:
      TZ: Europe/Paris
      NGINX_HOST: iam
      NGINX_PORT: 443
    volumes:
      - ../../certs/rucio_ca.pem:/etc/grid-security/certificates/5fca1cb1.0:z
      # - ../../certs/hostcert_rucio.pem:/etc/grid-security/hostcert.pem:z
      # - ../../certs/hostcert_rucio.key.pem:/etc/grid-security/hostkey.pem:z
      - /etc/grid-security/:/etc/grid-security/
      - /dev/urandom:/dev/random
      - ../../iam-assets/iam.conf:/etc/nginx/conf.d/default.conf:ro
  iam:
    profiles:
      - iam
    image: indigoiam/iam-login-service:v1.8.2
    volumes:
      - ../../iam-assets/keystore.jwks:/keystore.jwks:ro
    environment:
      - IAM_JAVA_OPTS=-Djava.security.egd=file:/dev/urandom -Dspring.profiles.active=prod,oidc,cern,registration,wlcg-scopes -agentlib:jdwp=transport=dt_socket,server=y,address=1044,suspend=n -Dlogging.file.name=/var/log/iam/iam.log
      - IAM_HOST=<IAM_HOSTNAME>
      - IAM_PORT=8090
      - IAM_BASE_URL=https://<IAM_HOSTNAME>
      - IAM_ISSUER=https://<IAM_HOSTNAME>
      - IAM_FORWARD_HEADERS_STRATEGY=native
      - IAM_KEY_STORE_LOCATION=file:/keystore.jwks
      - IAM_JWK_CACHE_LIFETIME=21600
      # - IAM_X509_TRUST_ANCHORS_DIR=/etc/grid-security/certificates
      # - IAM_X509_TRUST_ANCHORS_REFRESH=14400
      - IAM_TOMCAT_ACCESS_LOG_ENABLED=false
      - IAM_TOMCAT_ACCESS_LOG_DIRECTORY=/tmp
      - IAM_ACTUATOR_USER_USERNAME=user
      - IAM_ACTUATOR_USER_PASSWORD=secret
      - IAM_LOCAL_RESOURCES_ENABLE=true
      - IAM_LOCAL_RESOURCES_LOCATION=file:/indigo-iam/local-resources
      - IAM_ORGANISATION_NAME=rucio-dc
      - IAM_TOPBAR_TITLE="INDIGO IAM for rucio-dc"
      - IAM_DB_HOST=<IAM_DB_HOSTNAME>
      - IAM_DB_PORT=3307
      - IAM_DB_NAME=iam_db
      - IAM_DB_USERNAME=iam
      - IAM_DB_PASSWORD=secret
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    platform: linux/x86_64
    profiles:
      - kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    #ports:
    #  - 22181:2181
  kafka:
    image: confluentinc/cp-server:latest
    platform: linux/x86_64
    #hostname: kafka
    container_name: kafka
    #network_mode: "service:rucio"
    profiles:
      - kafka
    depends_on:
      - zookeeper
   # ports:
   #   - "9092:9092"
   #   - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    volumes:
      - ../../../../test_data:/opt/rucio/test_data
  testenv-ingestd:
    image: testenv-ingestd:1.1
    profiles:
      - kafka
    environment:
      CTRL_INGESTD_CONFIG: /home/lsst/ctrl_ingestd/etc/ingestd.yml
    #network_mode: "service:rucio"
    volumes:
      - /tmp/ingestd:/tmp/
      - ../../../../disks:/rucio/disks
      - ../../../../ctrl_ingestd:/home/lsst/ctrl_ingestd
      - ../../../../tmp_new:/home/lsst/tmp_new
      - ../../../../test_data:/home/lsst/test_data
    command: ["tail", "-f", "/dev/null"]
  test-register:
    container_name: test-register
    image: test-register
    volumes:
      - /tmp/register:/tmp/
      - ../../../../disks:/rucio/disks
      - ../../../../dm_rucio_register:/home/lsst/dm_rucio_register
      - ../../../../ctrl_ingestd:/home/lsst/ctrl_ingestd
      - ../../../../embargo-butler:/home/lsst/embargo-butler
      - ../../../../tmp_new:/home/lsst/tmp_new
      - ../../../../test_data:/home/lsst/test_data
      - ../../../../rucio_sup:/home/lsst/rucio_sup
      - ../../ctrl_rucio_ingest/etc/rucio.cfg:/opt/rucio/etc/rucio.cfg:z
      - ../../certs/rucio_ca.pem:/etc/grid-security/certificates/5fca1cb1.0:z
      - ../../certs/hostcert_rucio.pem:/etc/grid-security/hostcert.pem:z
      - ../../certs/hostcert_rucio.key.pem:/etc/grid-security/hostkey.pem:z
      - ../../certs/rucio_ca.pem:/opt/rucio/etc/rucio_ca.pem:z
      - ../../certs/ruciouser.pem:/opt/rucio/etc/usercert.pem:z
      - ../../certs/ruciouser.key.pem:/opt/rucio/etc/userkey.pem:z
      - ../../certs/ruciouser.certkey.pem:/opt/rucio/etc/usercertkey.pem:z
      - ../../certs/ssh/ruciouser_sshkey.pub:/root/.ssh/ruciouser_sshkey.pub:z
      - ../../certs/ssh/ruciouser_sshkey:/root/.ssh/ruciouser_sshkey:z
      - ../../../../ctrl_rucio_ingest/etc/rucio.cfg:/opt/rucio/etc/rucio.cfg:z
      - ../../../../../.exrc:/opt/rucio/.exrc:z
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    platform: linux/x86_64
    profiles:
      - kafka
    # network_mode: "service:rucio"
    environment:
      KAFKA_BROKER_CONNECT: kafka:9092
      SERVER_PORT: 9550
      MANAGEMENT_SERVER_PORT: 9550
  hermesk:
    image: rucio-daemons-hermesk:33.5.0.1
    profiles:
      - kafka
    environment:
      - RUCIO_DAEMON=hermesk
    volumes:
      - ../../../../ctrl_rucio_ingest/etc/rucio.cfg:/opt/rucio/etc/rucio.cfg:Z
      - ../../../../rucio/etc/certs/rucio_ca.pem:/etc/grid-security/certificates/5fca1cb1.0:Z
      - ../../../:/rucio_source:ro
    #entrypoint: ["/rucio_source/etc/docker/dev/rucio_entrypoint.sh"]
    #command: ["sleep", "infinity"]
