name: Build Rucio/Butler ingestd container

on:
  merge_group: {}
  pull_request: {}
  push:
    tags:
      - "*"

env:
  HERMESK_NAME: rucio-daemons-hermesk

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    inputs:
      context: docker
      dockerfile: docker/Dockerfile
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build ingest image
        uses: lsst-sqre/build-and-push-to-ghcr@v1
        id: build
        with:
          image: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - run: echo Pushed ghcr.io/${{ github.repository }}:${{ steps.build.outputs.tag }}
