name: Build Rucio HermesK container
on:
  push:
    tags:
    - '**'
  pull_request:

env:
  HERMESK_NAME: rucio-daemons-hermesk

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set tag-based Docker tag
      id: tag
      run: |
        GIT_TAG="${GITHUB_REF_NAME}"
        VERSION=$(echo "$GIT_TAG" | sed 's#[^a-zA-Z0-9_.-]#-#g')
        echo "VERSION=$VERSION" >> $GITHUB_ENV


    - name: Echo the Docker tag name
      run: |
         echo "Docker image will be tagged as ${VERSION}"

    - name: Build ingest image
      working-directory: docker
      run: |
        docker compose -f "docker-compose.yml" --env-file versions.env build $HERMESK_NAME

    - name: Log in to GitHub Container Registry 
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Push image
      run: |
        HERMESK_ID=ghcr.io/${{ github.repository_owner }}/$HERMESK_NAME

        # Strip git ref prefix from version
        echo HERMESK_ID=$HERMESK_ID
        echo VERSION=$VERSION
        docker tag $HERMESK_NAME $HERMESK_ID:$VERSION
        docker push $HERMESK_ID:$VERSION
